# Xanthan Configuration
title: Xanthan
version: 1.0.0
baseurl:
analytics_id:
search: true
theme_css: canyon-wall

exclude:
  - CLAUDE.md
  - CHANGELOG.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
